### ISSUE TITLE
本地编辑器查看问题

### ISSUE THREAD

**Issue by zema1** [geekrainy/hexo-tag-imgurl#1]
首先，这个插件不错，我之前都是手动改主题文件加个replace来实现类似功能的。但一直以来有个问题，就是用这种方法就没法用本地的markdown编辑器查看图片了，不知您有没有什么好的想法。

**Comment by geekrainy** [comment]
我自己的方式是使用 `hexo s` 直接在浏览器中配合 `hexo-browsersync` 插件来预览。因为主题和编辑器的样式也有很大差异，所以采用这种方式。:)

**Comment by zema1** [comment]
Get 新技能，Thanks~
